// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyscmpemgdnifdebptie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5c2NtcGVtZ2RuaWZkZWJwdGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTM1NzYsImV4cCI6MjA2NjAyOTU3Nn0.H5eA4ej_mOgk_4hvEtoc52crB1cy5qz4X5TQoEzAcec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);